### ISSUE TITLE
how to show my orders data in calendar 

### ISSUE THREAD

**Issue by akashsky44** [twinssbc/Ionic-Calendar#144]
i integrate twinssbc/Ionic-Calendar in my project. i want to show my orders list display like evetnts show when i click on date show orders details i give to u my controller code but i dont understand how to do. i am trying but it not display anything.
![capture](https://user-images.githubusercontent.com/17689498/26864472-f85f7dbc-4b75-11e7-9f96-f3fd2d1d6d81.JPG)
![newcapture](https://user-images.githubusercontent.com/17689498/26864473-f864191c-4b75-11e7-8422-c4f2c28da0ae.JPG)

**Comment by twinssbc** [comment]
@akashsky44 It's probably due to the eventDetail section is using ion-content, so it occupies the rest of the height. Could you try explicitly set the height see if any element below it can be displayed? 
You could also use monthviewEventDetailTemplateUrl option to provide your own event details section to not use the ion-content.
```
.event-detail-container {
    height: 100px;
}
```

**Comment by akashsky44** [comment]
How to disable previous and future days in month view by blank value how to do this.
![capture](https://user-images.githubusercontent.com/17689498/26879640-84e4876c-4baf-11e7-8086-a496b1b229d9.JPG)
