### ISSUE TITLE
Translate the calendar and display month and year

### ISSUE THREAD

**Issue by romulus001** [twinssbc/Ionic-Calendar#167]
Hello, I have 2 issues I'm trying to fix :
1- How to change the title of the days? I need to replace "Mon" by "L", "Tue" by "M", "Wed" by M", "Thu" by "J", "Fri" by "V", "Sat" by "S" and "Sun" by "D"
2- How to display and translate the month and year currently displayed in the calendar? I already translated the months in the app.module.ts file

Here you have a screenshot of my page with the calendar![ionic-calendar](https://user-images.githubusercontent.com/31893216/33081733-4da652bc-cedb-11e7-92de-c1c99cb865d1.PNG)

The link to my html page [https://github.com/romulus001/MSS/blob/master/voir-calendrier.html](url)
and the link to its ts file [https://github.com/romulus001/MSS/blob/master/voir-calendrier.ts](url)
Thanks by advance.

**Comment by twinssbc** [comment]
@romulus001 I think you are using Ionic2-Calendar, right? I guess you created the issue under wrong repository. 
Since your translation is not supported by the default DatePipe, you could use a custom **dateFormatter**. You could find more details in README.
I'm going to close it. If you need more help, you could create the issue under https://github.com/twinssbc/Ionic2-Calendar/issues
