### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by joseangelmr** [twinssbc/Ionic-Calendar#24]
Hello, 

I'm using the Calendar demo, there is a way a use calendar.tpls.js?, i.e. use templates.html directly. Make changes in view of calendar.tpls.js is tedious.

Thanks you

**Comment by twinssbc** [comment]
@joseangelmr The calendar.tpls.js stores all the template  html to the templateCache service, so that you don't need to on demand load these htmls. If you prefer loading html files on demand, that's also possible. You just need to make sure the html files are under the correct path so that the browser won't return 404 error.
