### ISSUE TITLE
How can I open the calendar day view to a particular date?

### ISSUE THREAD

**Issue by bmwertman** [twinssbc/Ionic-Calendar#47]
I have a list view of events. When someone selects a event in the list I want to open the day view to the date of that event.

**Comment by twinssbc** [comment]
@bmwertman 
I guess this event list is a separate view, instead of the event list in the month view?
So you need to change the currentDate to the date of the selected event and switch the calendar in the day view;
Assume you declare the calendar as below.
In your controller method, you can modify calendar.currentDate and calendar.mode.

```
            <calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource"
                      range-changed="reloadSource(startTime, endTime)"
                      event-selected="onEventSelected(event)" title-changed="onViewTitleChanged(title)"
                      time-selected="onTimeSelected(selectedTime)" step="30"></calendar>
```

**Comment by bmwertman** [comment]
@twinssbc 

Yes, the event list is a separate view. And your recommendation works for my use case. Thanks!
