### ISSUE TITLE
customized monthviewDisplayEvent.html template and slide action

### ISSUE THREAD

**Issue by bartsimp** [twinssbc/Ionic-Calendar#82]
customizing the month cell with 

`<div>{{view.dates[row*7+col].label}}</div><div>. . .</div>`

when I slide the month to the next (or prev), the cells shows only the day number and not my custom template

**Comment by twinssbc** [comment]
@bartsimp Could you provide the snippet that how you specify the template option?

**Comment by bartsimp** [comment]
actually I checkout the branch 0.3.0 and used the demo code.
I have not done changes except edit dist/js/calendar-tpls.js as follow:

`+++ dist/js/calendar-tpls.js
@@ -1285,7 +1285,7 @@ angular.module("templates/rcalendar/month.html", []).run(["$templateCache", func

 angular.module("templates/rcalendar/monthviewDisplayEvent.html", []).run(["$templateCache", function($templateCache) {
   $templateCache.put("templates/rcalendar/monthviewDisplayEvent.html",
-    "{{view.dates[row*7+col].label}}");
+    "<div>{{view.dates[row*7+col].label}}</div><div>. . .</div>");
 }]);
`
and open in browser demo/index.html

**Comment by twinssbc** [comment]
@bartsimp I tested and can see the extra div under the day number.
Could you use browser dev tool to check if it's not loading template file from some where else?
Also check the extra div in the template is not hidden?
Actually you don't need to modify the template directly, version 0.3.0 allows you to directly pass an external template url.

**Comment by bartsimp** [comment]
I try to explain with this screenshot

![screen](https://cloud.githubusercontent.com/assets/5881271/18364397/72c270a2-760e-11e6-84c7-d1df2ff7646d.png)

as you can see, while I slide from september to october the template is not used (instead is applied when the slide action is finished)

In addition there is a problem with heights . the events overlap to calendar.
It is just my problem?

**Comment by twinssbc** [comment]
@bartsimp 
This is because I don't apply the same template to the previous/next month.
It simply just renders the day number. Because there's no event associated, there's no need to apply a template on it.
You can apply some customised css to make the height of the cell are the same in previous/current/next month.
If you want to also display the same content in previous/next month, you can modify the below code snippet in the month.html.

```
                <tr ng-repeat="row in [0,1,2,3,4,5]">
                    <td ng-repeat="col in [0,1,2,3,4,5,6]">{{view.dates[row*7+col].label}}
                    </td>
                </tr>
```

Regarding your second question, this is there's a css class "event-detail-container" applied to event detail, it has the margin-top set to 262px, which is the height of the day number section. Since you add more contents in the day number sections, the height is changed. You can adjust the margin-top of event-detail-container to accommodate the new height.

**Comment by bartsimp** [comment]
thanks!
