### ISSUE TITLE
weekview cell color not changed

### ISSUE THREAD

**Issue by adnanjarfy** [twinssbc/Ionic-Calendar#96]
thank you for your great work, 
on weekview the color of the cell not changed when it get clicked
it raise the event but color not changed.

**Comment by twinssbc** [comment]
@adnanjarfy Yes, I didn't add logic to change the display of clicked cell.
The reason that selected cell in the month view gets changed, is because it can indicate which date is selected and list all the events selected on that date.
But in weekview, it already lists all events.

**Comment by adnanjarfy** [comment]
@twinssbc thank you for replay

**Comment by twinssbc** [comment]
@adnanjarfy I'm afraid you need to modify the source code.
First you need to expose a selected field for each cell so that you can use ng-class to add customised style based on the selected field.
Next you need to modify the select method in the weekview to set the selected state for the clicked cell and reset other cells' state.
You can refer to the similar logic in the monthview.

**Comment by adnanjarfy** [comment]
@twinssbc thank you so much
